services:
  awscdk:
    image: mlops-club/awscdk-minecraft-server
    command: deploy --app 'python /app/app.py'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_REGION: us-west-2
      AWS_PROFILE: minecraft
    user: root
    volumes:
      - ~/.aws:/root/.aws
      - ~/.aws:/users/pn/.aws
      - ~/.aws:/.aws
      - ~/.aws:/home/pn/.aws